server:
  port: 51001
spring:
  application:
    name: xc-rigistry
eureka:
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 60000 #每隔60s清理一次服务注册表
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:51001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 120.53.10.117
